### PR TITLE
PR: [BUG] Fix CommonsController delete that does not allow deleting user with associated profit table

### LINKED ISSUE #26: Bug Fix for Delete User from Commons

### PR DESCRIPTION
**Pull request by dakotazoid56**
## Overview
In this PR, I fixed a bug that would throw an error when attempting to call the: 

CommonsController:  @Operation(summary="Delete a user from a commons")

The problem was due to a dependent table associated with the user in the Profit section, that would not delete.  To fix this I added deleteByUserCommons to the ProfitRepository, and called the function inside the CommonsController delete user function. I additionally had to add a @Transactional header, import the transactional annotation, and Autowired the profitRepository. 

## Screenshots

BUG:
Screenshot 2024-05-21 at 3 03 08 PM

FIX: 
Screenshot 2024-05-21 at 2 59 49 PM

## Feedback Request
- Let me know if this fix looks good? 
- Also need to make sure that when the Profits are deleted, everything on the profit side is handled okay.

## Validation 
1. Download this branch.
2. Run the project.
3. Go to this page.
4. Test this function in Swagger. 
5. Make sure the Profit section works well after the fix. 

## Tests

- [x] Backend Unit tests (`mvn test`) pass
- [x] Backend Test coverage (`mvn test jacoco:report`) 100%
- [x] Backend Mutation tests (`mvn test pitest:mutationCoverage`) 100% 

## Linked Issues

Closes #26

### CODE REVIEW

**Review by nbelle1 — DISMISSED** [review]
LGTM

File: src/main/java/edu/ucsb/cs156/happiercows/repositories/ProfitRepository.java [hunk 1]
```diff
@@ -8,4 +8,6 @@
 @Repository
 public interface ProfitRepository extends CrudRepository<Profit, Long> {
     Iterable<Profit> findAllByUserCommons(UserCommons userCommons);
+    void deleteByUserCommons(UserCommons userCommons); // Add this line
```
Comment (sangitakunapuli) [inline src/main/java/edu/ucsb/cs156/happiercows/repositories/ProfitRepository.java:11]: Please remove this comment

**Review by sangitakunapuli — CHANGES_REQUESTED** [review]
Looks good, please remove the unnecessary comment

**Review by pconrad — APPROVED** [review]
LGTM!
